(ns nomio.widgets.mongol
  (:require ["package:flutter/material.dart" :as m]
            ["package:mongol/mongol.dart" :as mgl]
            [nomio.theme :as theme]))

(defn text
  ([s] (text s {}))
  ([s {:keys [size color weight]
       :or {size 16.0 color theme/ink}}]
   (mgl/MongolText
    (or s "")
    .style (m/TextStyle .fontSize (double size)
                        .color color
                        .fontWeight weight
                        .fontFamily theme/font-family))))

(defn muted [s]
  (text s {:size 13.0 :color theme/ink-faint}))
